### ISSUE TITLE
Helm chart should have an option to specify general resource requirements and limits ( to support GPU inference )

### ISSUE THREAD

**Issue by NotMatthewGriffin** [Striveworks/LIteCOW#1]
The current LIteCOW project has support for using gpus but the helm chart does not add the right resource requirements/limits to allow for the service to scale up on gpus. 

A new entry should be added to the values.yaml of the helm chart to enable the specification of any resource requirements or limits. An entry that could be used to support GPU inference would look like:

```
resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
```

Additionally comments describing how to enable gpu support through these resource requirements can be added.
