### ISSUE TITLE
S3 accesskey and secretkey should be stored in secrets

### ISSUE THREAD

**Issue by NotMatthewGriffin** [Striveworks/LIteCOW#2]
Currently the s3 accesskey and secretkey specified in the helm chart values.yaml are stored directly as environment variables in the icow ksvc. In order to follow best practices these should be placed into kubernetes secrets used as environment variables like: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

An example of how the ksvc yaml env section will look with the proposed change:

```
env:
      - name: AWS_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3-access
            key: accesskey
      - name: AWS_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: s3-access
            key: secretkey
      - name: S3ENDPOINT_URL
          value: {{ .Values.s3.endpoint }}
```
